// This file is auto-generated by react-native-prebuilt-e2e-helper
//
// To update this file, run:
//
//   npx react-native-prebuilt-e2e-helper update-aliases -p <path to project>
//
// You can also add your own aliases to this file manually.
//
// For more information, see:
//
//   https://github.com/facebook/react-native/blob/main/packages/react-native-prebuilt-e2e-helper/README.md
//
export {};
